[book]
authors = ["UebelAndre"]
language = "en"
multilingual = false
src = "src"
title = "rules_js_rust_wasm_bindgen"

[output.html]
git-repository-url = "https://github.com/UebelAndre/rules_js_rust_wasm_bindgen"
